-- ================================================================
-- KITS FLEXIVEIS - ESTRUTURA SUPABASE
-- ================================================================
-- Esta modelagem evita duplicar preco de produto.
-- O kit guarda apenas estrutura, categorias relacionadas e itens.
-- O preco continua vindo sempre da tabela "produtos".

begin;

create table if not exists public.kits (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    nome text not null,
    descricao_curta text,
    ativo boolean not null default true,
    destaque_home boolean not null default false,
    desconto_tipo text not null default 'none'
        check (desconto_tipo in ('none', 'min_items_percent')),
    desconto_min_itens integer
        check (desconto_min_itens is null or desconto_min_itens >= 1),
    desconto_percentual numeric(5,2)
        check (desconto_percentual is null or (desconto_percentual >= 0 and desconto_percentual <= 100)),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint kits_desconto_consistente check (
        (desconto_tipo = 'none' and desconto_min_itens is null and desconto_percentual is null)
        or
        (desconto_tipo = 'min_items_percent' and desconto_min_itens is not null and desconto_percentual is not null)
    )
);

create table if not exists public.kit_itens (
    id bigint generated by default as identity primary key,
    kit_id bigint not null references public.kits(id) on delete cascade,
    produto_id bigint not null references public.produtos(id) on delete restrict,
    ordem integer not null default 0,
    created_at timestamptz not null default now(),
    unique (kit_id, produto_id)
);

create table if not exists public.kit_categorias (
    id bigint generated by default as identity primary key,
    kit_id bigint not null references public.kits(id) on delete cascade,
    categoria text not null,
    created_at timestamptz not null default now(),
    unique (kit_id, categoria)
);

create index if not exists idx_kits_ativo on public.kits (ativo);
create index if not exists idx_kits_destaque_home on public.kits (destaque_home);
create index if not exists idx_kit_itens_kit_id on public.kit_itens (kit_id);
create index if not exists idx_kit_itens_produto_id on public.kit_itens (produto_id);
create index if not exists idx_kit_categorias_kit_id on public.kit_categorias (kit_id);
create index if not exists idx_kit_categorias_categoria on public.kit_categorias (categoria);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_kits_set_updated_at on public.kits;
create trigger trg_kits_set_updated_at
before update on public.kits
for each row
execute function public.set_updated_at();

alter table public.kits enable row level security;
alter table public.kit_itens enable row level security;
alter table public.kit_categorias enable row level security;

drop policy if exists "kits_public_read" on public.kits;
create policy "kits_public_read"
on public.kits
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "kit_itens_public_read" on public.kit_itens;
create policy "kit_itens_public_read"
on public.kit_itens
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.kits
        where public.kits.id = public.kit_itens.kit_id
          and public.kits.ativo = true
    )
);

drop policy if exists "kit_categorias_public_read" on public.kit_categorias;
create policy "kit_categorias_public_read"
on public.kit_categorias
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.kits
        where public.kits.id = public.kit_categorias.kit_id
          and public.kits.ativo = true
    )
);

commit;

-- ================================================================
-- EXEMPLO DE CADASTRO
-- ================================================================
-- 1. Crie o kit
-- insert into public.kits
--     (slug, nome, descricao_curta, destaque_home, desconto_tipo, desconto_min_itens, desconto_percentual)
-- values
--     ('kit-utilidades-dia-a-dia', 'Kit Utilidades do Dia a Dia', 'Monte sua combinacao com itens praticos.', true, 'min_items_percent', 5, 5);
--
-- 2. Relacione o kit com categorias onde ele deve aparecer
-- insert into public.kit_categorias (kit_id, categoria)
-- values
--     (1, 'Utilidades'),
--     (1, 'Escolar');
--
-- 3. Relacione os produtos que podem entrar nesse kit
-- insert into public.kit_itens (kit_id, produto_id, ordem)
-- values
--     (1, 10, 1),
--     (1, 12, 2),
--     (1, 15, 3);
